# Note that many of these secrets have been previously created in the keycloak setup deployment
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-kafka-broker-client-secret
  namespace: kafka # where you want the new secret
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: css-eso-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka-broker-client
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client-id: 'kafka-broker'
        client-secret: '{{ .retrievedpassword }}' # Helm escaped variant: '{{"{{ .retrievedpassword }}"}}'
  data:
    - secretKey: retrievedpassword # Key used for lookup in templating above in target section
      remoteRef:
        key: keycloak-kafka-broker-client-pushed-secret
        property: keycloak-kafka-broker-client-secret-value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-kafka-schema-registry-client-secret
  namespace: kafka # where you want the new secret
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: css-eso-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka-schema-registry-client
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client-id: 'schema-registry'
        client-secret: '{{ .retrievedpassword }}' # Helm escaped variant: '{{"{{ .retrievedpassword }}"}}'
  data:
    - secretKey: retrievedpassword # Key used for lookup in templating above in target section
      remoteRef:
        key: keycloak-kafka-schema-registry-client-pushed-secret
        property: keycloak-kafka-schema-registry-client-secret-value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-kafka-tenant-a-client-secret
  namespace: kafka # where you want the new secret
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: css-eso-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka-tenant-a-client
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client-id: 'tenant-a'
        client-secret: '{{ .retrievedpassword }}' # Helm escaped variant: '{{"{{ .retrievedpassword }}"}}'
  data:
    - secretKey: retrievedpassword # Key used for lookup in templating above in target section
      remoteRef:
        key: keycloak-kafka-tenant-a-client-pushed-secret
        property: keycloak-kafka-tenant-a-client-secret-value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-kafka-tenant-b-client-secret
  namespace: kafka # where you want the new secret
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: css-eso-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka-tenant-b-client
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client-id: 'tenant-b'
        client-secret: '{{ .retrievedpassword }}' # Helm escaped variant: '{{"{{ .retrievedpassword }}"}}'
  data:
    - secretKey: retrievedpassword # Key used for lookup in templating above in target section
      remoteRef:
        key: keycloak-kafka-tenant-b-client-pushed-secret
        property: keycloak-kafka-tenant-b-client-secret-value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-kafka-admin-user-password
  namespace: kafka # where you want the new secret
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: css-eso-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka-admin-user
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # username: 'admin'
        password: '{{ .retrievedpassword }}' # Helm escaped variant: '{{"{{ .retrievedpassword }}"}}'
  data:
    - secretKey: retrievedpassword # Key used for lookup in templating above in target section
      remoteRef:
        key: keycloak-kafka-admin-user-pushed-secret
        property: keycloak-kafka-admin-user-password-value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-kafbat-ui-sals-jaas-connection-config-secret
  namespace: kafka # where you want the new secret
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: css-eso-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kafbat-ui-sals-jaas-connection-config-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        sasl-jaas-config: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required oauth.valid.issuer.uri="http://keycloak.localho.st:8080/realms/kafka" oauth.jwks.endpoint.uri="http://keycloak.keycloak.svc.cluster.local:8080/realms/kafka/protocol/openid-connect/certs" clientId=kafka-broker scope='openid' clientSecret={{ .retrievedpassword }};
        # '{{ .retrievedpassword }}' # Helm escaped variant: '{{"{{ .retrievedpassword }}"}}'
  data:
    - secretKey: retrievedpassword # Key used for lookup in templating above in target section
      remoteRef:
        key: keycloak-kafka-broker-client-pushed-secret
        property: keycloak-kafka-broker-client-secret-value
