apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: eso-pwgen-keycloak
  namespace: ns-external-secrets-in-cluster-store
spec:
  length: 42
  digits: 5
  symbols: 5
  symbolCharacters: "-_"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: eso-ps-keycloak-bootstrap-admin-pw
  namespace: ns-external-secrets-in-cluster-store # Same NS as generator resource
spec:
  # refreshInterval: 6h0m0s # Doesn't work (just commenting this out)
  # updatePolicy: IfNotExists # Doesn't work
  refreshInterval: "0"
  secretStoreRefs:
    - name: css-eso-cluster-secret-store
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: eso-pwgen-keycloak # Matches generator name defined above
  data:
    - match:
        secretKey: password # property in the generator output, is "password" for generator type password
        remoteRef:
          remoteKey: keycloak-bootstrap-admin-pushed-secret # Remote reference (where the secret is going to be pushed)
          property: keycloak-bootstrap-admin-pw-value # the property to use to push into
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-kc-bootstrap-admin-secret
  namespace: keycloak # where you want the new secret
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: css-eso-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kc-bootstrap-admin
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # username: 'admin'
        password: '{{ .retrievedpassword }}' # Helm escaped variant: '{{"{{ .retrievedpassword }}"}}'
  data:
    - secretKey: retrievedpassword # Key used for lookup in templating above in target section
      remoteRef:
        key: keycloak-bootstrap-admin-pushed-secret
        property: keycloak-bootstrap-admin-pw-value
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: eso-ps-keycloak-database-pw
  namespace: ns-external-secrets-in-cluster-store # Same NS as generator resource
spec:
  # refreshInterval: 6h0m0s # Doesn't work (just commenting this out)
  # updatePolicy: IfNotExists # Doesn't work
  refreshInterval: "0"
  secretStoreRefs:
    - name: css-eso-cluster-secret-store
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: eso-pwgen-keycloak # Matches generator name defined above
  data:
    - match:
        secretKey: password # property in the generator output, is "password" for generator type password
        remoteRef:
          remoteKey: keycloak-database-pw-pushed-secret # Remote reference (where the secret is going to be pushed)
          property: keycloak-database-pw-value # the property to use to push into
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-kc-database-secret
  namespace: keycloak # where you want the new secret
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: css-eso-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kc-db
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # username: 'keycloak'
        password: '{{ .retrievedpassword }}' # Helm escaped variant: '{{"{{ .retrievedpassword }}"}}'
  data:
    - secretKey: retrievedpassword # Key used for lookup in templating above in target section
      remoteRef:
        key: keycloak-database-pw-pushed-secret
        property: keycloak-database-pw-value
