apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: eso-pwgen-client-secrets
  namespace: ns-external-secrets-in-cluster-store
spec:
  length: 12
  digits: 5
  symbols: 0
  symbolCharacters: "-"
  noUpper: true
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: eso-pwgen-kafka-user-password
  namespace: ns-external-secrets-in-cluster-store
spec:
  length: 18
  digits: 5
  symbols: 4
  symbolCharacters: "-_"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: eso-ps-keycloak-kafka-broker-client-secret
  namespace: ns-external-secrets-in-cluster-store # Same NS as generator resource
spec:
  # refreshInterval: 6h0m0s # Doesn't work (just commenting this out)
  # updatePolicy: IfNotExists # Doesn't work
  refreshInterval: "0"
  secretStoreRefs:
    - name: css-eso-cluster-secret-store
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: eso-pwgen-client-secrets # Matches generator name defined above
  data:
    - match:
        secretKey: password # property in the generator output, is "password" for generator type password
        remoteRef:
          remoteKey: keycloak-kafka-broker-client-pushed-secret # Remote reference (where the secret is going to be pushed)
          property: keycloak-kafka-broker-client-secret-value # the property to use to push into
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-kafka-broker-client-secret
  namespace: keycloak # where you want the new secret
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: css-eso-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka-broker-client
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client-id: 'kafka-broker'
        client-secret: '{{ .retrievedpassword }}' # Helm escaped variant: '{{"{{ .retrievedpassword }}"}}'
  data:
    - secretKey: retrievedpassword # Key used for lookup in templating above in target section
      remoteRef:
        key: keycloak-kafka-broker-client-pushed-secret
        property: keycloak-kafka-broker-client-secret-value
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: eso-ps-keycloak-kafka-schema-registry-client-secret
  namespace: ns-external-secrets-in-cluster-store # Same NS as generator resource
spec:
  # refreshInterval: 6h0m0s # Doesn't work (just commenting this out)
  # updatePolicy: IfNotExists # Doesn't work
  refreshInterval: "0"
  secretStoreRefs:
    - name: css-eso-cluster-secret-store
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: eso-pwgen-client-secrets # Matches generator name defined above
  data:
    - match:
        secretKey: password # property in the generator output, is "password" for generator type password
        remoteRef:
          remoteKey: keycloak-kafka-schema-registry-client-pushed-secret # Remote reference (where the secret is going to be pushed)
          property: keycloak-kafka-schema-registry-client-secret-value # the property to use to push into
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-kafka-schema-registry-client-secret
  namespace: keycloak # where you want the new secret
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: css-eso-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka-schema-registry-client
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client-id: 'schema-registry'
        client-secret: '{{ .retrievedpassword }}' # Helm escaped variant: '{{"{{ .retrievedpassword }}"}}'
  data:
    - secretKey: retrievedpassword # Key used for lookup in templating above in target section
      remoteRef:
        key: keycloak-kafka-schema-registry-client-pushed-secret
        property: keycloak-kafka-schema-registry-client-secret-value
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: eso-ps-keycloak-kafka-tenant-a-client-secret
  namespace: ns-external-secrets-in-cluster-store # Same NS as generator resource
spec:
  # refreshInterval: 6h0m0s # Doesn't work (just commenting this out)
  # updatePolicy: IfNotExists # Doesn't work
  refreshInterval: "0"
  secretStoreRefs:
    - name: css-eso-cluster-secret-store
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: eso-pwgen-client-secrets # Matches generator name defined above
  data:
    - match:
        secretKey: password # property in the generator output, is "password" for generator type password
        remoteRef:
          remoteKey: keycloak-kafka-tenant-a-client-pushed-secret # Remote reference (where the secret is going to be pushed)
          property: keycloak-kafka-tenant-a-client-secret-value # the property to use to push into
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-kafka-tenant-a-client-secret
  namespace: keycloak # where you want the new secret
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: css-eso-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka-tenant-a-client
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client-id: 'kafka-tenant-a'
        client-secret: '{{ .retrievedpassword }}' # Helm escaped variant: '{{"{{ .retrievedpassword }}"}}'
  data:
    - secretKey: retrievedpassword # Key used for lookup in templating above in target section
      remoteRef:
        key: keycloak-kafka-tenant-a-client-pushed-secret
        property: keycloak-kafka-tenant-a-client-secret-value
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: eso-ps-keycloak-kafka-tenant-b-client-secret
  namespace: ns-external-secrets-in-cluster-store # Same NS as generator resource
spec:
  # refreshInterval: 6h0m0s # Doesn't work (just commenting this out)
  # updatePolicy: IfNotExists # Doesn't work
  refreshInterval: "0"
  secretStoreRefs:
    - name: css-eso-cluster-secret-store
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: eso-pwgen-client-secrets # Matches generator name defined above
  data:
    - match:
        secretKey: password # property in the generator output, is "password" for generator type password
        remoteRef:
          remoteKey: keycloak-kafka-tenant-b-client-pushed-secret # Remote reference (where the secret is going to be pushed)
          property: keycloak-kafka-tenant-b-client-secret-value # the property to use to push into
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-kafka-tenant-b-client-secret
  namespace: keycloak # where you want the new secret
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: css-eso-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka-tenant-b-client
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client-id: 'kafka-tenant-b'
        client-secret: '{{ .retrievedpassword }}' # Helm escaped variant: '{{"{{ .retrievedpassword }}"}}'
  data:
    - secretKey: retrievedpassword # Key used for lookup in templating above in target section
      remoteRef:
        key: keycloak-kafka-tenant-b-client-pushed-secret
        property: keycloak-kafka-tenant-b-client-secret-value
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: eso-ps-keycloak-kafka-admin-user-password
  namespace: ns-external-secrets-in-cluster-store # Same NS as generator resource
spec:
  # refreshInterval: 6h0m0s # Doesn't work (just commenting this out)
  # updatePolicy: IfNotExists # Doesn't work
  refreshInterval: "0"
  secretStoreRefs:
    - name: css-eso-cluster-secret-store
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: eso-pwgen-kafka-user-password # Matches generator name defined above
  data:
    - match:
        secretKey: password # property in the generator output, is "password" for generator type password
        remoteRef:
          remoteKey: keycloak-kafka-admin-user-pushed-secret # Remote reference (where the secret is going to be pushed)
          property: keycloak-kafka-admin-user-password-value # the property to use to push into
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-kafka-admin-user-password
  namespace: keycloak # where you want the new secret
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: css-eso-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka-admin-user
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # username: 'admin'
        password: '{{ .retrievedpassword }}' # Helm escaped variant: '{{"{{ .retrievedpassword }}"}}'
  data:
    - secretKey: retrievedpassword # Key used for lookup in templating above in target section
      remoteRef:
        key: keycloak-kafka-admin-user-pushed-secret
        property: keycloak-kafka-admin-user-password-value
