autoscaling:
  vertical:
    enabled: false

clusterCollector:
  enabled: true
  additionalMetricLabels: {}
  replicas: 2
  resources: {}
  scrapeInterval: 30s
  targetAllocator:
    replicas: 2
    resources: {}
  telemetry:
    logs:
      level: warn

kafka:
  bootstrapServer: ""
  compression:
    type: zstd # options are none, gzip, snappy, lz4, and zstd
    params:
      # compression level used, see https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/kafkaexporter#configuration-settings
      level: 11
  secretName: "kafka-otel-user-secret"
  topics:
    logs: ""
    metrics: ""
    traces: ""

otlpCollector:
  enabled: true
  # these are in the form key: value
  additionalLabels: {}
  exporters:
    # this pushes the metrics received over otlp back to the local prometheus server running in the cluster
    prometheusOtlp:
      enabled: true
      endpoint: "http://prometheus-kube-prometheus-prometheus.prometheus-operator:9090/api/v1/otlp"
  replicas: 2
  resources: {}
  telemetry:
    logs:
      level: warn

opentelemetry-operator:
  revisionHistoryLimit: 1
  fullnameOverride: operator
  manager:
    image:
      repository: container-registry.example.com/ghcr/open-telemetry/opentelemetry-operator/opentelemetry-operator
    collectorImage:
      repository: container-registry.example.com/ghcr/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
    targetAllocatorImage:
      repository: container-registry.example.com/ghcr/open-telemetry/opentelemetry-operator/target-allocator
    featureGatesMap:
      operator.targetallocator.mtls: true
    extraArgs:
      - "--metrics-secure=false"
    resources: {}
    serviceMonitor:
      enabled: true
      extraLabels:
        release: prometheus
    prometheusRule:
      enabled: true
      extraLabels:
        release: prometheus
      defaultRules:
        enabled: true
    createRbacPermissions: true
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    supplementalGroups:
      - 100
  admissionWebhooks:
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - "argocd"
            - "default"
            - "kube-node-lease"
            - "kube-public"
            - "kube-system"
            - "monitoring"
            - "prometheus-blackbox-exporter"
            - "prometheus-operator"
