{
 "title": "Tempo - Backend Work",
 "tags": [
  "tempo",
  "tempo-dev"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "metrics", "label": "Metrics", "query": "prometheus" },
   { "name": "logs", "label": "Logs", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(tempo_build_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(tempo_build_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Blocklist Maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blocklist Length",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(tempodb_blocklist_length{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (tenant)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Blocklist Poll Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_blocklist_poll_duration_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_blocklist_poll_duration_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_blocklist_poll_duration_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Retention duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_retention_duration_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_retention_duration_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_retention_duration_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) )",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Retention",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(tempodb_retention_deleted_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "deleted"
    },
    {
     "expr": "sum(increase(tempodb_retention_marked_for_deletion_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "marked_for_deletion"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Active",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(tempo_backend_scheduler_jobs_active{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(tempo_backend_scheduler_jobs_completed_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(tempo_backend_scheduler_jobs_failed_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retry",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(tempo_backend_scheduler_jobs_retry{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Found",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(tempo_backend_scheduler_jobs_not_found_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merged Jobs / h",
   "type": "timeseries",
   "description": "Jobs merged from the providers into the work stream.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(tempo_backend_scheduler_provider_jobs_merged_total{namespace=~\"$namespace\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compaction Tenant Empty Job / 10m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(tempo_backend_scheduler_compaction_tenant_empty_job_total{namespace=~\"$namespace\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compaction Jobs Created / 10m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(tempo_backend_scheduler_compaction_jobs_created_total{namespace=~\"$namespace\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Compactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Outstanding Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(tempodb_compaction_outstanding_blocks{namespace=~\"$namespace\"}) by (container, tenant)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Objects Written / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_objects_written_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (level)"
    }
   ]
  },
  {
   "title": "Objects Combined / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_objects_combined_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (level)"
    }
   ]
  },
  {
   "title": "Blocks Compacted 10m Window",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(tempodb_compaction_blocks_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[10m])) by (level)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Written / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_bytes_written_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (level)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compaction Tenant Resets / 1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(tempo_backend_scheduler_compaction_tenant_reset_total{namespace=~\"$namespace\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources - Backend-scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Backend-scheduler CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"backend-scheduler\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"backend-scheduler\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"backend-scheduler\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"backend-scheduler\",resource=\"cpu\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Backend-scheduler Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"backend-scheduler\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"backend-scheduler\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"backend-scheduler\",resource=\"memory\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_customresource_vpa_recommendations_target{resource=\"memory\", namespace=~\"$namespace\", container=\"backend-scheduler\"})",
     "legendFormat": "vpa recommendation"
    }
   ]
  },
  { "title": "Resources - Backend-worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Backend-worker Autoscaling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "min(kube_horizontalpodautoscaler_status_desired_replicas{namespace=~\"$namespace\", horizontalpodautoscaler=\"keda-hpa-backend-worker\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min(kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$namespace\", horizontalpodautoscaler=\"keda-hpa-backend-worker\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min(kube_horizontalpodautoscaler_spec_max_replicas{namespace=~\"$namespace\", horizontalpodautoscaler=\"keda-hpa-backend-worker\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min(kube_horizontalpodautoscaler_spec_min_replicas{namespace=~\"$namespace\", horizontalpodautoscaler=\"keda-hpa-backend-worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Worker Autoscaling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "min(kube_horizontalpodautoscaler_spec_target_metric{namespace=~\"$namespace\", horizontalpodautoscaler=\"keda-hpa-backend-worker\"})",
     "legendFormat": "Target Autoscaling Metric"
    },
    {
     "expr": "min(kube_horizontalpodautoscaler_status_target_metric{namespace=~\"$namespace\", horizontalpodautoscaler=\"keda-hpa-backend-worker\"})",
     "legendFormat": "Actual Autoscaling Metric"
    }
   ]
  },
  {
   "title": "Backend-worker CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"backend-worker\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"backend-worker\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"backend-worker\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"backend-worker\",resource=\"cpu\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Backend-worker Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"backend-worker\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"backend-worker\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"backend-worker\",resource=\"memory\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_customresource_vpa_recommendations_target{resource=\"memory\", namespace=~\"$namespace\", container=\"backend-worker\"})",
     "legendFormat": "vpa recommendation"
    }
   ]
  }
 ]
}