networks:
  apps_network:
    attachable: true
    name: apps_network
    ipam:
      driver: default
      config:
        - subnet: "172.80.80.0/24"
        - subnet: "2001:8080:8080::/64"
services:
  create-observability-stack-configs:
    image: debian:stable-slim
    user: 1000:1001
    container_name: create-observability-stack-configs
    depends_on:
      set-up-container-mount-area:
        required: true
        restart: false
        condition: service_completed_successfully
    volumes:
      - .:/ProjectDir
    environment:
      RECREATE_IF_EXISTS: "false"
    entrypoint:
      - '/bin/bash'
      - '-c'
      - |
        echo '================ Creating directory structure ============================='
        mkdir -p /ProjectDir/ContainerData
        if [ ! -f /ProjectDir/ContainerData/.gitignore ]; then
          echo 'Creating gitignore so that you dont accidentally check in container data'
          echo 'If you want some of the container data checked in, simply add an exception to the gitignore'
          printf '%s\n' '*' '#!.gitignore' > /ProjectDir/ContainerData/.gitignore
        fi
        mkdir -p /ProjectDir/ContainerData/ObservabilityStackConfig
        cd /ProjectDir/ContainerData/ObservabilityStackConfig
        mkdir -p /ProjectDir/ContainerData/ObservabilityStackConfig/grafana
        mkdir -p /ProjectDir/ContainerData/ObservabilityStackConfig/grafana/datasources
        mkdir -p /ProjectDir/ContainerData/ObservabilityStackConfig/grafana-loki
        mkdir -p /ProjectDir/ContainerData/ObservabilityStackConfig/grafana-mimir
        mkdir -p /ProjectDir/ContainerData/ObservabilityStackConfig/grafana-tempo
        mkdir -p /ProjectDir/ContainerData/ObservabilityStackConfig/opentelemetry-collector
        echo '================ Done Creating directory structure ========================'
        # In the section below, note that cat <<'EOF' makes the output literal without bash attempting transforms,
        # but still need to escape $ with $$, so outputted $$ has to be rewritten to $$$$ here.
        echo '================ Creating Grafana Ini Config ============================='
        cat <<'EOF' > /ProjectDir/ContainerData/ObservabilityStackConfig/grafana/grafana.ini
        [auth]:
        disable_login_form: false

        [auth.anonymous]:
        enabled: true
        org_role: Admin

        [log]:
        mode: console
        level: error

        [feature_toggles]:
        enable: traceqlEditor traceQLStreaming metricsSummary tempoApmTable traceToMetrics

        [analytics]:
        enabled: false
        reporting_enabled: false
        check_for_updates: false
        check_for_plugin_updates: false
        EOF
        echo '================ Done Creating Grafana Ini Config ========================'

        echo '================ Creating Grafana Data Sources Config ============================='
        cat <<'EOF' > /ProjectDir/ContainerData/ObservabilityStackConfig/grafana/datasources/datasources.yaml
        apiVersion: 1

        datasources:
          - name: Loki
            type: loki
            uid: Loki
            url: http://grafana-loki:3100
            editable: true
            jsonData:
              derivedFields:
                - datasourceUid: "Tempo"
                  matcherRegex: "trace_id"
                  matcherType: "label"
                  name: "trace_id"
                  url: "$$$${__value.raw}"
          - name: Mimir
            type: prometheus
            uid: Mimir
            url: http://grafana-mimir:9009/prometheus
            editable: true
            jsonData:
              httpMethod: POST
              exemplarTraceIdDestinations:
                - datasourceUid: Tempo
                  name: trace_id
              prometheusType: Mimir
              prometheusVersion: 2.9.1
          - name: Tempo
            type: tempo
            uid: Tempo
            url: http://grafana-tempo:3200
            editable: true
            jsonData:
              httpMethod: GET
              nodeGraph:
                enabled: true
              search:
                filters:
                  - id": service-name
                    operator: =
                    scope: resource
                    tag: service.name
                  - id: span-name
                    operator: =
                    scope: span
                    tag: name
              serviceMap:
                datasourceUid: Mimir
              tracesToLogsV2:
                customQuery: true
                datasourceUid: Loki
                filterByTraceID: false
                query: '{$$$${__tags}} | trace_id="$$$${__trace.traceId}"'
                spanEndTimeShift: 30s
                spanStartTimeShift: -30s
                tags:
                  - key: service.name
                    value: service_name
        EOF
        echo '================ Done Creating Grafana Data Sources Config ========================'

        echo '================ Creating Grafana Loki Config ============================='
        cat <<'EOF' > /ProjectDir/ContainerData/ObservabilityStackConfig/grafana-loki/config.yaml
        auth_enabled: false

        server:
          http_listen_port: 3100
          grpc_listen_port: 9096
          log_level: error

        common:
          instance_addr: 127.0.0.1
          path_prefix: /tmp/loki
          storage:
            filesystem:
              chunks_directory: /tmp/loki/chunks
              rules_directory: /tmp/loki/rules
          replication_factor: 1
          ring:
            kvstore:
              store: inmemory

        query_range:
          results_cache:
            cache:
              embedded_cache:
                enabled: true
                max_size_mb: 100

        schema_config:
          configs:
            - from: 2020-10-24
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: index_
                period: 24h

        limits_config:
          allow_structured_metadata: true

        analytics:
          reporting_enabled: false
        EOF
        echo '================ Done Creating Grafana Loki Config ========================'

        echo '================ Creating Grafana Mimir Config ============================='
        cat <<'EOF' > /ProjectDir/ContainerData/ObservabilityStackConfig/grafana-mimir/config.yaml
        # Do not use this configuration in production.
        # It is for demonstration purposes only.
        multitenancy_enabled: false

        memberlist:
          bind_addr:
            - 127.0.0.1
          join_members:
            - grafana-mimir-gossip-ring:7946

        blocks_storage:
          backend: filesystem
          bucket_store:
            sync_dir: /tmp/mimir/tsdb-sync
          filesystem:
            dir: /tmp/mimir/data/tsdb
          tsdb:
            dir: /tmp/mimir/tsdb

        compactor:
          data_dir: /tmp/mimir/compactor
          sharding_ring:
            kvstore:
              store: memberlist

        distributor:
          ring:
            instance_addr: 127.0.0.1
            kvstore:
              store: memberlist

        ingester:
          ring:
            instance_addr: 127.0.0.1
            kvstore:
              store: memberlist
            replication_factor: 1

        ruler_storage:
          backend: filesystem
          filesystem:
            dir: /tmp/mimir/rules

        server:
          http_listen_port: 9009
          log_level: error

        store_gateway:
          sharding_ring:
            replication_factor: 1

        limits:
          max_global_exemplars_per_user: 10000

        usage_stats:
          enabled: false
        EOF
        echo '================ Done Creating Grafana Mimir Config ========================'

        echo '================ Creating Grafana Tempo Config ============================='
        cat <<'EOF' > /ProjectDir/ContainerData/ObservabilityStackConfig/grafana-tempo/config.yaml
        distributor:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: grafana-tempo:4317

        ingester:
          flush_check_period: 1s
          lifecycler:
            address: grafana-tempo
            min_ready_duration: 1s
            ring:
              kvstore:
                store: inmemory
              replication_factor: 1
          max_block_duration: 1s
          trace_idle_period: 1s

        metrics_generator:
          processor:
            local_blocks:
              filter_server_spans: false
            span_metrics:
              dimensions:
                - operation
                - service_name
                - status_code
          storage:
            path: /tmp/tempo/generator/wal
            remote_write:
              - url: http://grafana-mimir:9009/api/v1/push
                send_exemplars: true
          traces_storage:
            path: /tmp/tempo/generator/traces

        stream_over_http_enabled: true

        server:
          grpc_listen_port: 9096
          http_listen_port: 3200
          log_level: error

        querier:
          frontend_worker:
            frontend_address: grafana-tempo:9096

        storage:
          trace:
            backend: local
            local:
              path: /tmp/tempo/blocks
            wal:
              path: /tmp/tempo/wal

        overrides:
          metrics_generator_processors:
            - local-blocks
            - service-graphs
            - span-metrics

        usage_report:
          reporting_enabled: false

        EOF
        echo '================ Done Creating Grafana Tempo Config ========================'
        echo '================ Creating OpenTelemetry Collector Config ============================='
        # Nice guide for filtering: https://last9.io/blog/opentelemetry-configurations-filtering-sampling-enrichment/
        # Updated docs with correct syntax:
        # - Tail sampler: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/tailsamplingprocessor/README.md
        # - Filter: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/filterprocessor/README.md
        # Note you have to use the otel contrib variant of the collector image to get these running
        cat <<'EOF' > /ProjectDir/ContainerData/ObservabilityStackConfig/opentelemetry-collector/config.yaml
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: opentelemetry-collector:4317
              http:
                endpoint: opentelemetry-collector:4318

        processors:
          batch:
          memory_limiter:
            check_interval: 1s
            limit_mib: 1000
            spike_limit_mib: 100
          tail_sampling:
            decision_wait: 1s
            num_traces: 100_000
            expected_new_traces_per_sec: 10_000
            decision_cache:
              sampled_cache_size: 1_000_000
              non_sampled_cache_size: 1_000_000
            policies:
              [
                  {
                    # Always pass errors further on, don't drop them
                    name: status-code,
                    type: status_code,
                    status_code: { status_codes: [ERROR] },
                  },
                  {
                    name: composite-policy-1,
                    type: composite,
                    composite:
                    {
                      max_total_spans_per_second: 100,
                      policy_order:
                      [
                        composite-name-match-1,
                        composite-name-match-2,
                        composite-name-match-3,
                        composite-name-match-4,
                        composite-name-match-5,
                        composite-pass-rest
                      ],
                      composite_sub_policy:
                        [
                          { name: composite-name-match-1, type: ottl_condition, ottl_condition: { error_mode: ignore, span: [ 'name == "Span.First"' ], spanevent: [] } },
                          { name: composite-name-match-2, type: ottl_condition, ottl_condition: { error_mode: ignore, span: [ 'name == "Span.Second"' ], spanevent: [] } },
                          { name: composite-name-match-3, type: ottl_condition, ottl_condition: { error_mode: ignore, span: [ 'name == "Spand.Second.Subspan"' ], spanevent: [] } },
                          { name: composite-name-match-4, type: ottl_condition, ottl_condition: { error_mode: ignore, span: [ 'name == "Span.Third.Subspan"' ], spanevent: [] } },
                          { name: composite-name-match-5, type: ottl_condition, ottl_condition: { error_mode: ignore, span: [ 'name == "Span.Third"' ], spanevent: [] } },
                          { name: composite-pass-rest, type: always_sample }
                        ],
                      rate_allocation:
                        [
                          { policy: composite-name-match-1, percent: 5 },
                          { policy: composite-name-match-2, percent: 10 },
                          { policy: composite-name-match-3, percent: 10 },
                          { policy: composite-name-match-4, percent: 10 },
                          { policy: composite-name-match-5, percent: 10 },
                          { policy: composite-pass-rest, percent: 100 }
                        ]
                    }
                  }
              ]
          filter:
            # Don't bother with samling health check event data, these are for kubernetes/docker, low value on telemetry end
            error_mode: ignore
            traces:
              span:
                - IsMatch(resource.attributes["http.url"], ".*/health")
            logs:
              log_record:
                - 'IsMatch(body, "healthy")'
                - 'severity_number < SEVERITY_NUMBER_WARN'

        exporters:
          otlphttp/loki:
            endpoint: http://grafana-loki:3100/otlp
          otlphttp/mimir:
            endpoint: http://grafana-mimir:9009/otlp
          otlp/tempo:
            endpoint: grafana-tempo:4317
            tls:
              insecure: true

        extensions:
          health_check:

        service:
          extensions: [health_check]
          pipelines:
            logs:
              receivers: [otlp]
              processors: [memory_limiter, batch]
              exporters: [otlphttp/loki]
            metrics:
              receivers: [otlp]
              processors: [memory_limiter, batch]
              exporters: [otlphttp/mimir]
            traces:
              receivers: [otlp]
              processors: [memory_limiter, tail_sampling, filter, batch]
              exporters: [otlp/tempo]
          telemetry:
            logs:
              level: debug
        EOF
        echo '================ Done Creating OpenTelemetry Collector Config ========================'
  grafana:
    image: grafana/grafana:12.1.0
    depends_on:
      create-observability-stack-configs:
        required: true
        restart: false
        condition: service_completed_successfully
    ports:
      - 3000:3000
    networks:
      - apps_network
    volumes:
      - ./ContainerData/ObservabilityStackConfig/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./ContainerData/ObservabilityStackConfig/grafana/datasources:/etc/grafana/provisioning/datasources
  grafana-loki:
    image: grafana/loki:3.5
    depends_on:
      create-observability-stack-configs:
        required: true
        restart: false
        condition: service_completed_successfully
    command: ["-config.file=/etc/config.yaml"]
    networks:
      - apps_network
    volumes:
      - ./ContainerData/ObservabilityStackConfig/grafana-loki/config.yaml:/etc/config.yaml
  grafana-mimir:
    image: grafana/mimir:2.16.1
    depends_on:
      create-observability-stack-configs:
        required: true
        restart: false
        condition: service_completed_successfully
    command: ["-config.file=/etc/config.yaml"]
    networks:
      - apps_network
    volumes:
      - ./ContainerData/ObservabilityStackConfig/grafana-mimir/config.yaml:/etc/config.yaml
  grafana-tempo:
    image: grafana/tempo:2.7.2
    depends_on:
      create-observability-stack-configs:
        required: true
        restart: false
        condition: service_completed_successfully
    command: ["-config.file=/etc/config.yaml"]
    networks:
      - apps_network
    volumes:
      - ./ContainerData/ObservabilityStackConfig/grafana-tempo/config.yaml:/etc/config.yaml
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.130.1
    ports:
      - 4317:4317
      - 4318:4318
      - 9201:9201
    command: ["--config=/etc/config.yaml"]
    networks:
      - apps_network
    volumes:
      - ./ContainerData/ObservabilityStackConfig/opentelemetry-collector/config.yaml:/etc/config.yaml
    depends_on:
      - grafana-loki
      - grafana-mimir
      - grafana-tempo
