apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-kafbat-ui.fullname" . }}
  labels:
    {{- include "kafka-kafbat-ui.labels" . | nindent 4 }}
  # name: kafka-kafbat-ui-configmap
data:
  KAFKA_CLUSTERS_0_NAME: {{.Values.configMap.HELM_VAR_KAFKA_CLUSTERS_0_NAME | quote}}
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: {{.Values.configMap.HELM_VAR_KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS | quote}}
  KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED: {{.Values.configMap.HELM_VAR_KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED | quote}}
  KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED: {{.Values.configMap.HELM_VAR_KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED | quote}}
  KAFKA_CLUSTERS_0_AUDIT_TOPIC: {{.Values.configMap.HELM_VAR_KAFKA_CLUSTERS_0_AUDIT_TOPIC | quote}}
  KAFKA_CLUSTERS_0_AUDIT_AUDITTOPICPROPERTIES_RETENTION_MS: {{.Values.configMap.HELM_VAR_KAFKA_CLUSTERS_0_AUDIT_AUDITTOPICPROPERTIES_RETENTION_MS | quote}}
  KAFKA_CLUSTERS_0_AUDIT_AUDITTOPICPROPERTIES_RETENTION_BYTES: {{.Values.configMap.HELM_VAR_KAFKA_CLUSTERS_0_AUDIT_AUDITTOPICPROPERTIES_RETENTION_BYTES | quote}}
  KAFKA_CLUSTERS_0_AUDIT_AUDITTOPICSPARTITIONS: {{.Values.configMap.HELM_VAR_KAFKA_CLUSTERS_0_AUDIT_AUDITTOPICSPARTITIONS | quote}}
  KAFKA_CLUSTERS_0_AUDIT_LEVEL: {{.Values.configMap.HELM_VAR_KAFKA_CLUSTERS_0_AUDIT_LEVEL | quote}}
  LOGGING_LEVEL_ROOT: {{.Values.configMap.HELM_VAR_LOGGING_LEVEL_ROOT | quote}}
  LOGGING_LEVEL_IO_KAFBAT_UI: {{.Values.configMap.HELM_VAR_LOGGING_LEVEL_IO_KAFBAT_UI | quote}}
