apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-kafbat-ui.fullname" . }}
  labels:
    {{- include "kafka-kafbat-ui.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: {{ .Values.reloader.auto | quote }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "kafka-kafbat-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Ensures dpeloyment is labeled as out of sync if config map chages
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kafka-kafbat-ui.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kafka-kafbat-ui.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: pod-port-http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          # env:
          #   - name: "EXAMPLE_ADDITIONAL_DIRECT_ENV_VAR"
          #     value: "the syntax looks like this"
          #   - name: "EXAMPLE_DIRECT_ENV_VAR_FROM_SECRET"
          #     valueFrom:
          #       secretKeyRef:
          #         name: very-awesome-secret
          #         key: a-thing-with-a-secret-value
          envFrom:
            - configMapRef:
                name: {{ include "kafka-kafbat-ui.fullname" . | quote}}
            {{- range .Values.secretsPutInEnv }}
            - secretRef:
                name: {{ . |quote }}
            {{- end}}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
