apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-kafbat-ui.fullname" . }}
  labels:
    {{- include "kafka-kafbat-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pod-port-http
      protocol: TCP
      name: http
  selector:
    {{- include "kafka-kafbat-ui.selectorLabels" . | nindent 4 }}
