apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-kafbat-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocdProject }}
  destination:
    name: "in-cluster"
    namespace: {{ .Values.kafka.namespace }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: kafka-kafbat-ui
    repoURL: https://example.com/this-repo
    targetRevision: main
