{{- /* Create generator with config resulting in passwords suitable for grafana web login */}}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: eso-grafana-password-generator
  namespace: eso-secret-storage
spec:
  length: 42
  digits: 5
  symbols: 5
  symbolCharacters: "-_"
  noUpper: false
  allowRepeat: true
---
{{- /* Generate new password for grafana's web admin */}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-grafana-admin-password
  namespace: eso-secret-storage
spec:
  # refreshInterval: 1h
  refreshPolicy: CreatedOnce
  target:
    name: generated-grafana-admin-pw-secret
    creationPolicy: Owner
    template:
      data:
        password: '{{"{{ .password }}"}}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: eso-grafana-password-generator
---
{{- /* Take the password secret and make it available the grafana web namespace for grafana */}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-grafana-admin-pw-secret
  namespace:  {{ .Values.grafanaHa.namespace }}
spec:
  # refreshInterval: 1h
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: eso-obsstack-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.grafanaHa.name }}-admin
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-user: 'admin'
        admin-password: '{{"{{ .password }}"}}'
  data:
    - secretKey: password # Key used for lookup in templating above in target section
      remoteRef:
        key: generated-grafana-admin-pw-secret # Name of secret in cluster secret store
        property: password # Key used in secret we extract from
---
{{- /* Take the password secret and make it available the grafana provisioner namespace for the provisioner to use */}}
# external-secret-copy.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-grafana-admin-pw-secret
  namespace:  {{ .Values.grafanaProvisioner.namespace }}
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: eso-obsstack-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.grafanaProvisioner.name }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        GRAFANA_USERNAME: 'admin'
        GRAFANA_PASSWORD: '{{"{{ .password }}"}}'
  data:
    - secretKey: password # Key used for lookup in templating above in target section
      remoteRef:
        key: generated-grafana-admin-pw-secret # Name of secret in cluster secret store
        property: password # Key used in secret we extract from
