apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-store-role
  namespace: external-secrets-operator-ns
rules:
  - apiGroups: [""]
    resources:
      - secrets
    # Get, list, and watch are needed for read access
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # This will allow the role `eso-store-role` to perform **permission reviews** for itself within the defined namespace:
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews # used to review or fetch the list of permissions a user or service account currently has.
    verbs:
      - create # `create` allows creating a `selfsubjectrulesreviews` request.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-service-account
  namespace: external-secrets-operator-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-eso-store-role-to-eso-service-account
  namespace: external-secrets-operator-ns
subjects:
  - kind: ServiceAccount
    name: eso-service-account
    namespace: external-secrets-operator-ns
roleRef:
  kind: ClusterRole
  name: eso-store-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: eso-obsstack-cluster-secret-store
  namespace: external-secrets-operator # any ns; the store can target multi‑svcAccount-ns
spec:
  provider:
    kubernetes:
      remoteNamespace: eso-secret-storage
      # Using a serviceAccount that can read the source secret
      auth:
        serviceAccount:
          name: eso-service-account
          namespace: external-secrets-operator-ns
      server:
        url: kubernetes.default
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: external-secrets-operator-ns
          key: ca.crt
---
{{- /* Create generator with config resulting in passwords suitable for PG and grafana */}}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: eso-pg-password-generator
  namespace: eso-secret-storage
spec:
  length: 42
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
---
{{- /* Generate new password for grafana's PG database */}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-grafana-db-password
  namespace: eso-secret-storage # where you want the new secret
spec:
  # refreshInterval: 1h
  refreshPolicy: CreatedOnce
  target:
    name: generated-grafana-db-secret
    creationPolicy: Owner
    template:
      data:
        password: '{{"{{ .password }}"}}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: eso-pg-password-generator
---
{{- /* Take the password secret and make it available the pg cluster namespace */}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-grafana-db-secret-for-pg
  namespace: {{ .Values.postgresCluster.namespace }} # where you want the new secret
spec:
  # refreshInterval: 1h
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: eso-obsstack-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: db-secret-grafana # name of new secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: 'grafana'
        password: '{{"{{ .password }}"}}'
  data:
    - secretKey: password # key used for lookup in templating above in target section
      remoteRef:
        key: generated-grafana-db-secret
        property: password # Key used in secret we extract from
---
{{- /* Take the password secret and make it available the pg cluster namespace */}}
# external-secret-copy.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: create-grafana-db-secret-for-grafana
  namespace: {{ .Values.grafanaHa.namespace }}
spec:
  # refreshInterval: 1h
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: eso-obsstack-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: db-secret-grafana
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: 'grafana'
        password: '{{"{{ .password }}"}}'
  data:
    - secretKey: password # key used for lookup in templating above in target section
      remoteRef:
        key: generated-grafana-db-secret
        property: password # Key used in secret we extract from
