{{- if ( and .Values.grafanaProvisioner.enabled .Values.tenants ) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.grafanaProvisioner.name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocdProject }}
  source:
    repoURL: container-registry.example.com/plattform-helm
    targetRevision: 0.0.84
    chart: grafana-provisioner
    helm:
      values: |
        environment: {{ .Values.grafanaProvisioner.environment }}
        grafanaUrl: {{ print ( .Values.grafana.name ) "." ( .Values.grafana.namespace ) ":80" }}
        opentelemetryCollectorEndpoint: "http://otlp-collector.opentelemetry:4318"
        datasources:
          alertmanager:
            {{- if .Values.mimir.useGateway }}
            url: {{ print "http://" .Values.mimir.name "-gateway." .Values.mimir.namespace ":80" }}
            {{- else }}
            url: {{ print "http://" .Values.mimir.name "-alertmanager." .Values.mimir.namespace  ":8080" }}
            {{- end }}
          loki:
            {{- if .Values.loki.useGateway }}
            url: {{ print "http://" .Values.loki.name "-gateway." .Values.loki.namespace ":80" }}
            {{- else }}
            url: {{ print "http://" .Values.loki.name "-query-frontend." .Values.loki.namespace ":3100" }}
            {{- end }}
          prometheus:
            {{- if .Values.mimir.useGateway }}
            url: {{ print "http://" .Values.mimir.name "-gateway." .Values.mimir.namespace ":80/prometheus" }}
            {{- else }}
            url: {{ print "http://" .Values.mimir.name "-query-frontend." .Values.mimir.namespace ":8080/prometheus" }}
            {{- end }}
          tempo:
            {{- if .Values.tempo.useGateway }}
            url: {{ print "http://" .Values.tempo.name "-gateway." .Values.tempo.namespace ":80" }}
            {{- else }}
            url: {{ print "http://" .Values.tempo.name "-query-frontend." .Values.tempo.namespace ":3200" }}
            {{- end }}
            streamingEnabled: {{ not .Values.tempo.useGateway }}
        {{- if .Values.tenants }}
        organizations:
        {{- range .Values.tenants }}
        {{- $_ := required "Team is required in tenant" .team }}
        {{- if not ( regexMatch "^team-[a-z-]+$" .team ) }}
        {{- fail "invalid value for team, must be prefixed with 'team-' and can only contain lowercase letters eg 'team-example'" }}
        {{- end }}
          - name: {{ .team }}
        {{- end }}
        {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.grafanaProvisioner.namespace }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
