{{- range .Values.tenants }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ print $.Values.opentelemetryCollector.name "-" .team }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.argocdProject }}
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.156.2
    chart: opentelemetry-collector
    helm:
      valuesObject:
        fullnameOverride: {{ print $.Values.opentelemetryCollector.name "-" .team }}
        mode: "deployment"
        {{- with (.opentelemetryCollector).replicas }}
        replicaCount: {{ . }}
        {{- end }}
        config:
          receivers:
            otlp: {}
            zipkin: {}
            jaeger: {}
            prometheus: {}
            {{- $bootstrapServer := "" }}
            {{- if ( eq $.Values.environment "prod" ) }}
            {{- $bootstrapServer = ( print "bootstrap.kafka.example.com:9094" ) }}
            {{- else }}
            {{- $bootstrapServer = ( print "bootstrap-" $.Values.environment ".kafka.example.com:9094" ) }}
            {{- end }}
            kafka:
              auth:
                tls:
                  ca_file: /kafka/tls/BrokerCaCertificate.pem
                  cert_file: /kafka/tls/UserCertificate.pem
                  key_file: /kafka/tls/UserKey.pem
              brokers:
                - {{ $bootstrapServer }}
              error_backoff:
                enabled: true
              group_id: {{ print "prefix-" $.Values.consumerGroupId }}
              {{- /* this needs to be set explisitly when using collector version >= 0.137.0 because the franz-go kafka library implementation sets no default value */}}
              group_rebalance_strategy: range
              logs:
                topics:
                  {{- if not ((.opentelemetryCollector).overrideTopics).logs }}
                  - {{ print "otel-" .team "-logs" }}
                  {{- else }}
                  {{- range $topicName := .opentelemetryCollector.overrideTopics.logs }}
                  - {{$topicName}}
                  {{- end }}{{- /* end range */}}
                  {{- end }}{{- /* end ifelse */}}
              message_marking:
                after: true
                on_error: true
              metrics:
                topics:
                  {{- if not ((.opentelemetryCollector).overrideTopics).metrics }}
                  - {{ print "otel-" .team "-metrics" }}
                  {{- else }}
                  {{- range $topicName := .opentelemetryCollector.overrideTopics.metrics }}
                  - {{$topicName}}
                  {{- end }}{{- /* end range */}}
                  {{- end }}{{- /* end ifelse */}}
              protocol_version: 2.1.0
              traces:
                topics:
                  {{- if not ((.opentelemetryCollector).overrideTopics).traces }}
                  - {{ print "otel-" .team "-traces" }}
                  {{- else }}
                  {{- range $topicName := .opentelemetryCollector.overrideTopics.traces }}
                  - {{$topicName}}
                  {{- end }}{{- /* end range */}}
                  {{- end }}{{- /* end ifelse */}}
          processors:
            {{- /*
            The batch processor is enabled by default in the upstream helm chart.
            Newer versions of the collector recommend configuring batching in the exporter.sending_queue parameter,
            so we remove the processor config from the chart by sending an empty map.
            */}}
            batch: {}
            {{- /*
            The memory_limiter processor is enabled by default in the upstream helm chart.
            We do not need it in our case since we do not want to drop records from kafka if memory usage is close to limit,
            we should rather get OOMKilled and start reading the topic on restart.
            */}}
            memory_limiter: {}
          exporters:
            otlp_http/loki:
              endpoint: http://{{ $.Values.loki.name }}-distributor.{{ $.Values.loki.namespace }}:3100/otlp
              headers:
                "X-Scope-OrgId": {{ .team }}
              retry_on_failure:
                {{- /* Setting this ensures infinite retries */}}
                max_elapsed_time: 0s
              sending_queue:
                batch: {}
            otlp_http/mimir-ingest:
              endpoint: http://{{ $.Values.mimirIngest.name }}-distributor.{{ $.Values.mimirIngest.namespace }}:8080/otlp
              headers:
                "X-Scope-OrgId": {{ .team }}
              retry_on_failure:
                {{- /* Setting this ensures infinite retries */}}
                max_elapsed_time: 0s
              sending_queue:
                batch: {}
            otlp_grpc/tempo:
              endpoint: {{ $.Values.tempo.name }}-distributor.{{ $.Values.tempo.namespace }}:4317
              headers:
                "X-Scope-OrgId": {{ .team }}
              retry_on_failure:
                {{- /* Setting this ensures infinite retries */}}
                max_elapsed_time: 0s
              sending_queue:
                batch: {}
              tls:
                insecure: true
            debug: {}
          service:
            pipelines:
              logs:
                receivers:
                  - kafka
                {{- /* We need to set this to an empty array because it is set in the upstream helm chart */}}
                processors: []
                exporters:
                  - otlp_http/loki
              metrics:
                receivers:
                  - kafka
                {{- /* We need to set this to an empty array because it is set in the upstream helm chart */}}
                processors: []
                exporters:
                  - otlp_http/mimir-ingest
              traces:
                receivers:
                  - kafka
                {{- /* We need to set this to an empty array because it is set in the upstream helm chart */}}
                processors: []
                exporters:
                  - otlp_grpc/tempo
            telemetry:
              logs:
                encoding: {{ $.Values.logFormat }}
                level: {{ $.Values.logLevel }}
              metrics:
                readers:
                  - pull:
                      exporter:
                        prometheus:
                          host: ${env:MY_POD_IP}
                          port: 8888
                          without_type_suffix: true
              {{- if $.Values.enableTracing }}
              traces:
                propagators:
                  - "tracecontext"
                  - "b3"
                processors:
                  - batch:
                      exporter:
                        otlp:
                          protocol: grpc/protobuf
                          endpoint: http://{{ $.Values.internalCollectorDomainName }}:4317
              {{- end }}
        image:
          repository: {{ $.Values.registryGhcr }}/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector
        command:
          name: "otelcol"
        podSecurityContext:
          seccompProfile:
            type: RuntimeDefault
          supplementalGroups:
            - 100
        securityContext:
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsGroup: 10001
        extraVolumes:
          - name: kafka
            secret:
              secretName: kafka-otel-user-secret
        extraVolumeMounts:
          - name: kafka
            readOnly: true
            mountPath: /kafka/tls
        ports:
          otlp:
            enabled: false
          otlp-http:
            enabled: false
          jaeger-compact:
            enabled: false
          jaeger-thrift:
            enabled: false
          jaeger-grpc:
            enabled: false
          zipkin:
            enabled: false
          metrics:
            enabled: true
        useGOMEMLIMIT: false
        resources:
          {{- toYaml $.Values.opentelemetryCollector.resources | nindent 10 }}
        revisionHistoryLimit: {{ $.Values.revisionHistoryLimit }}
        serviceMonitor:
          enabled: true
          {{- /* This label is added so that the resources are picked up by the prometheus operator */}}
          extraLabels:
            release: prometheus
        prometheusRule:
          enabled: true
          defaultRules:
            enabled: true
          {{- /* This label is added so that the resources are picked up by the prometheus operator */}}
          extraLabels:
            release: prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.opentelemetryCollector.namespace }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
{{- if $.Values.opentelemetryCollector.autoscaling.vertical.enabled }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ print $.Values.opentelemetryCollector.name "-" .team }}
  namespace: {{ $.Values.opentelemetryCollector.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ print $.Values.opentelemetryCollector.name "-" .team }}
  updatePolicy:
    updateMode: {{ $.Values.opentelemetryCollector.autoscaling.vertical.updateMode | quote }}
{{- end }}
---
{{- $_ := required "Environment is required" $.Values.environment }}
{{- if ( not ( or ( eq $.Values.environment "test" ) ( eq $.Values.environment "prod" ) ) ) }}
{{- fail "invalid value for environment, must be either 'test' or 'prod'" }}
{{- end }}
{{- $_ := required "Team is required in tenant" .team }}
{{- if ( not ( regexMatch "^team-[a-z]+(?:[-][a-z]+)*$" .team ) ) }}
{{- fail "invalid value for team, must be prefixed with 'team-' and can only contain lowercase letters eg 'team-plattform'" }}
{{- end }}
{{- end }}
{{- $_ := required "Location is required" .Values.location }}
{{- if ( not ( or ( eq .Values.location "trd" ) ( eq .Values.location "osl" ) ) ) }}
{{- fail "invalid value for location, must be either 'trd' or 'osl'" }}
{{- end }}
