# # Note that many of these secrets have been previously created in the keycloak setup deployment
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: create-kafbat-ui-kafka-client-secret
# spec:
#   refreshPolicy: CreatedOnce
#   secretStoreRef:
#     name: css-eso-cluster-secret-store
#     kind: ClusterSecretStore
#   target:
#     name: kafbat-ui-kafka-client
#     creationPolicy: Owner
#     template:
#       type: Opaque
#       data:
#         client-id: 'kafka-broker'
#         client-secret: '{{ .retrievedpassword }}' # Helm escaped variant: '{{"{{ .retrievedpassword }}"}}'
#   data:
#     - secretKey: retrievedpassword # Key used for lookup in templating above in target section
#       remoteRef:
#         key: keycloak-kafka-kafbat-ui-client-pushed-secret
#         property: keycloak-kafka-kafbat-ui-client-secret-value
# ---
