{{- if .Values.clusterCollector.enabled }}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: cluster
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - cluster-collector
          weight: 100
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: "otel-collector"
              scrape_interval: {{ .Values.clusterCollector.scrapeInterval }}
              static_configs:
                - targets:
                    - "0.0.0.0:8888"
    processors:
      {{- with .Values.clusterCollector.additionalMetricLabels }}
      attributes:
        actions:
          {{- range $key, $value := . }}
          - key: {{ $key }}
            value: {{ $value }}
            action: insert
          {{- end }}
      {{- end }}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    exporters:
      kafka:
        auth:
          tls:
            ca_file: /kafka/tls/BrokerCaCertificate.pem
            cert_file: /kafka/tls/UserCertificate.pem
            key_file: /kafka/tls/UserKey.pem
        brokers:
          - {{ .Values.kafka.bootstrapServer | quote }}
        metrics:
          topic: {{ .Values.kafka.topics.metrics | quote }}
        producer:
          {{- with .Values.kafka.compression }}
          compression: {{ .type }}
          compression_params:
            level: {{ .params.level }}
          {{- end }}
          required_acks: 0
        protocol_version: 2.1.0
        sending_queue:
          batch:
            {{- /*
            This sets the max size of the batches exported to kafka. We set it to 800 KiB.
            Setting this to 1MiB causes the messages to be too large for some reason.
            */}}
            max_size: 819200
            sizer: bytes
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    service:
      extensions:
        - health_check
      pipelines:
        metrics:
          receivers:
            - prometheus
          processors:
            - memory_limiter
            {{- if .Values.clusterCollector.additionalMetricLabels }}
            - attributes
            {{- end }}
          exporters:
            - kafka
      telemetry:
        logs:
          encoding: json
          level: {{ .Values.clusterCollector.telemetry.logs.level }}
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
                    without_type_suffix: true
  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
  mode: statefulset
  observability:
    metrics:
      enableMetrics: true
      extraLabels:
        release: prometheus
  podDisruptionBudget:
    maxUnavailable: 1
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
    supplementalGroups:
      - 100
  replicas: {{ .Values.clusterCollector.replicas }}
  resources:
    {{- toYaml .Values.clusterCollector.resources | nindent 4 }}
  securityContext:
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsGroup: 10001
  targetAllocator:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - cluster-targetallocator
            weight: 100
    enabled: true
    observability:
      metrics:
        enableMetrics: true
        extraLabels:
          release: prometheus
    podDisruptionBudget:
      maxUnavailable: 1
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
      supplementalGroups:
        - 100
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      probeSelector: {}
      scrapeConfigSelector: {}
      serviceMonitorSelector:
        matchExpressions:
          # We can not use the provided servicemonitor for the prometheus operator since we cannot load the ca.
          # We instead create a scrapeconfig where we skip ca verification. See https://github.com/open-telemetry/opentelemetry-operator/issues/3724.
          # We can also not use the kubelet service monitor. See https://github.com/open-telemetry/opentelemetry-operator/issues/3277.
          - key: app
            operator: NotIn
            values:
              - kube-prometheus-stack-operator
              - kube-prometheus-stack-kubelet
    replicas: {{ .Values.clusterCollector.targetAllocator.replicas }}
    resources:
      {{- toYaml .Values.clusterCollector.targetAllocator.resources | nindent 6 }}
    securityContext:
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsGroup: 10001
  volumes:
    - name: kafka
      secret:
        secretName: {{ .Values.kafka.secretName }}
  volumeMounts:
    - name: kafka
      readOnly: true
      mountPath: /kafka/tls
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-clustercollector
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
      - namespaces
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - "get"
      - "list"
      - "watch"
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-clustercollector
subjects:
  - kind: ServiceAccount
    name: cluster-collector
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: opentelemetry-clustercollector
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-targetallocator
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
      - namespaces
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - "get"
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - "get"
      - "list"
      - "watch"
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - "get"
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - podmonitors
      - scrapeconfigs
      - probes
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-targetallocator
subjects:
  - kind: ServiceAccount
    name: cluster-targetallocator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: opentelemetry-targetallocator
  apiGroup: rbac.authorization.k8s.io
{{- end }}
