s3Endpoint: "s3.example.com"
environment: "prod"
bucketPrefix: "otel-"
grafanaHa:
  additionalOrgMappings:
    - "team-example-token-role:team-example-organization:Editor"
    - "team-antother-example-oidc-role:team-best-organization:Viewer"
  fqdn: "grafana.example.com"
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
grafanaProvisioner:
  environment: Production
loki:
  retention: 90d
  canary:
    resources:
      requests:
        cpu: 1m
        memory: 32Mi
  chunksCache:
    replicas: 12
  compactor:
    resources:
      requests:
        cpu: 5m
        memory: 170Mi
  distributor:
    resources:
      requests:
        cpu: 15m
        memory: 95Mi
  gateway:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
  indexGateway:
    resources:
      requests:
        cpu: 3m
        memory: 160Mi
  ingester:
    replicas: 12
    resources:
      requests:
        cpu: 20m
        memory: 360Mi
  memcachedExporter:
    resources:
      limits:
        memory: 1512Mi
      requests:
        cpu: 2m
        memory: 128Mi
  querier:
    resources:
      requests:
        cpu: 14m
        memory: 128Mi
  queryFrontend:
    resources:
      requests:
        cpu: 5m
        memory: 375Mi
  queryScheduler:
    resources:
      requests:
        cpu: 4m
        memory: 50Mi
  resultsCache:
    replicas: 12
  ruler:
    resources:
      requests:
        cpu: 7m
        memory: 100Mi
  autoscaling:
    vertical:
      enabled: true
      updateMode: "Initial"
mimirIngest:
  retention: 1y
  alertmanager:
    resources:
      requests:
        cpu: 2m
        memory: 55Mi
  chunksCache:
    replicas: 12
  compactor:
    persistentVolume:
      size: 75Gi
    resources:
      requests:
        cpu: 9m
        memory: 175Mi
  distributor:
    replicas: 12
    resources:
      requests:
        cpu: 227m
        memory: 128Mi
  gateway:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
  indexCache:
    replicas: 12
  ingester:
    persistentVolume:
      size: 40Gi
    replicas: 15
    resources:
      requests:
        cpu: 225m
        memory: 8000Mi
  memcachedExporter:
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 50m
        memory: 128Mi
  metadataCache:
    replicas: 12
  overridesExporter:
    resources:
      requests:
        cpu: 2m
        memory: 34Mi
  querier:
    resources:
      requests:
        cpu: 6m
        memory: 350Mi
  queryFrontend:
    resources:
      requests:
        cpu: 6m
        memory: 160Mi
  queryScheduler:
    resources:
      requests:
        cpu: 3m
        memory: 38Mi
  resultsCache:
    replicas: 12
  ruler:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
  storeGateway:
    persistentVolume:
      size: 5Gi
    replicas: 12
    resources:
      requests:
        cpu: 12m
        memory: 128Mi
  autoscaling:
    vertical:
      enabled: true
      updateMode: "Initial"
opentelemetryCollector:
  resources:
    requests:
      cpu: 5m
      memory: 128Mi
  autoscaling:
    vertical:
      enabled: true
      updateMode: "Initial"
tempo:
  compactor:
    replicas: 12
    resources:
      requests:
        cpu: 4m
        memory: 1000Mi
  distributor:
    resources:
      requests:
        cpu: 5m
        memory: 240Mi
  ingester:
    replicas: 12
    resources:
      requests:
        cpu: 6m
        memory: 1700Mi
  memcached:
    replicas: 12
  memcachedExporter:
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 2m
        memory: 128Mi
  metricsGenerator:
    resources:
      requests:
        cpu: 15m
        memory: 1700Mi
  querier:
    replicas: 12
    resources:
      requests:
        cpu: 3m
        memory: 150Mi
  queryFrontend:
    resources:
      requests:
        cpu: 1m
        memory: 64Mi
  autoscaling:
    vertical:
      enabled: true
      updateMode: "Initial"
kafka:
  cluster:
    brokers:
      storage:
        size: 150Gi
tenants:
  - team: "team-admins"
  - team: "team-example"
