s3Endpoint: "s3.example.com"
environment: "test"
bucketPrefix: "otel-"
enableTracing: false
grafanaHa:
  additionalOrgMappings: []
  fqdn: "test.grafana.example.com"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
loki:
  canary:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
  compactor:
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
  distributor:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  gateway:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
  indexGateway:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
  ingester:
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
  memcachedExporter:
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 50m
        memory: 128Mi
  querier:
    resources:
      requests:
        cpu: 100m
        memory: 2048Mi
  queryFrontend:
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
  queryScheduler:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
  ruler:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
  autoscaling:
    vertical:
      enabled: true
mimirIngest:
  alertmanager:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  compactor:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  distributor:
    resources:
      requests:
        cpu: 500m
        memory: 1024Mi
  gateway:
    autoscaling:
      horizontal:
        enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
  ingester:
    resources:
      requests:
        cpu: 500m
        memory: 4096Mi
  memcachedExporter:
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 50m
        memory: 128Mi
  overridesExporter:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
  querier:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
  queryFrontend:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
  queryScheduler:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
  ruler:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
  storeGateway:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
  autoscaling:
    vertical:
      enabled: true
opentelemetryCollector:
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
  autoscaling:
    vertical:
      enabled: true
tempo:
  compactor:
    resources:
      requests:
        cpu: 100m
        memory: 1024Mi
  distributor:
    resources:
      requests:
        cpu: 50m
        memory: 1280Mi
  ingester:
    resources:
      requests:
        cpu: 75m
        memory: 2560Mi
  memcachedExporter:
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 50m
        memory: 128Mi
  metricsGenerator:
    resources:
      requests:
        cpu: 100m
        memory: 2048Mi
  querier:
    resources:
      requests:
        cpu: 200m
        memory: 1024Mi
  queryFrontend:
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
  autoscaling:
    vertical:
      enabled: true
tenants:
  - team: "team-admins"
    opentelemetryCollector:
      replicas: 10
      overrideTopics:
        metrics:
          - otel-team-admins-fixed-metrics
          - otel-team-admins-fixed-metrics-v2
  - team: "team-other-team"
