{{- if .Values.autoscaling.vertical.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ index .Values "opentelemetry-collector" "configMap" "existingName" }}
  namespace: {{ template "opentelemetry-collector.namespace" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ index .Values "opentelemetry-collector" "configMap" "existingName" }}
  updatePolicy:
    updateMode: "Auto"
{{- end }}
