# If setup with compose, you can run to use kubectl outside after:
# kind export kubeconfig --name demo-cluster
services:
  workshop:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: localhost/kind-cluster-script-runner:latest
    container_name: kind-cluster-script-setup-runner
    # command: ["./setup.sh"]
    environment:
      HOST_UID: "${HOST_UID}"
      HOST_GID: "${HOST_GID}"
    entrypoint:
      - '/bin/bash'
      - '-c'
      - |
        echo "$(ip route get 1.1.1.1 | awk '{print $NF; exit}') keycloak.localho.st" >> /etc/hosts

        ./setup.sh

        # Ensure extracted credentials for use directly from host are not owned by root and inaccessible to user:
        chown -R 777 /work/credentials

        # Leave container running, so that people without kind or kubectl can exec into it and use them from there:
        echo "Waiting forever, so that you have shell"
        tail -f /dev/null
    # user: "501:20"
    network_mode: host
    volumes:
      - .:/work
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true   # `docker compose run` gets a TTY
    tty: true
    # ports:
    #   - "2375:2375"
