// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UserAccessMapping.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace KafkaBlobChunking {

  /// <summary>Holder for reflection information generated from UserAccessMapping.proto</summary>
  public static partial class UserAccessMappingReflection {

    #region Descriptor
    /// <summary>File descriptor for UserAccessMapping.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserAccessMappingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdVc2VyQWNjZXNzTWFwcGluZy5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3Rp",
            "bWVzdGFtcC5wcm90byLhAQoRVXNlckFjY2Vzc01hcHBpbmcSEAoIQmxvYk5h",
            "bWUYASABKAkSDQoFT3duZXIYAiABKAkSFwoPQ2FuQ2hhbmdlQWNjZXNzGAMg",
            "AygJEhMKC0NhblJldHJpZXZlGAQgAygJEhEKCUNhbkNoYW5nZRgFIAMoCRIR",
            "CglDYW5EZWxldGUYBiADKAkSLQoJVXBkYXRlZEF0GAcgASgLMhouZ29vZ2xl",
            "LnByb3RvYnVmLlRpbWVzdGFtcBIRCglVcGRhdGVkQnkYCCABKAkSFQoNQ29y",
            "cmVsYXRpb25JZBgJIAEoCUIUqgIRS2Fma2FCbG9iQ2h1bmtpbmdiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::KafkaBlobChunking.UserAccessMapping), global::KafkaBlobChunking.UserAccessMapping.Parser, new[]{ "BlobName", "Owner", "CanChangeAccess", "CanRetrieve", "CanChange", "CanDelete", "UpdatedAt", "UpdatedBy", "CorrelationId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UserAccessMapping : pb::IMessage<UserAccessMapping>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UserAccessMapping> _parser = new pb::MessageParser<UserAccessMapping>(() => new UserAccessMapping());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UserAccessMapping> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::KafkaBlobChunking.UserAccessMappingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserAccessMapping() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserAccessMapping(UserAccessMapping other) : this() {
      blobName_ = other.blobName_;
      owner_ = other.owner_;
      canChangeAccess_ = other.canChangeAccess_.Clone();
      canRetrieve_ = other.canRetrieve_.Clone();
      canChange_ = other.canChange_.Clone();
      canDelete_ = other.canDelete_.Clone();
      updatedAt_ = other.updatedAt_ != null ? other.updatedAt_.Clone() : null;
      updatedBy_ = other.updatedBy_;
      correlationId_ = other.correlationId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserAccessMapping Clone() {
      return new UserAccessMapping(this);
    }

    /// <summary>Field number for the "BlobName" field.</summary>
    public const int BlobNameFieldNumber = 1;
    private string blobName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BlobName {
      get { return blobName_; }
      set {
        blobName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Owner" field.</summary>
    public const int OwnerFieldNumber = 2;
    private string owner_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Owner {
      get { return owner_; }
      set {
        owner_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CanChangeAccess" field.</summary>
    public const int CanChangeAccessFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_canChangeAccess_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> canChangeAccess_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> CanChangeAccess {
      get { return canChangeAccess_; }
    }

    /// <summary>Field number for the "CanRetrieve" field.</summary>
    public const int CanRetrieveFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_canRetrieve_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> canRetrieve_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> CanRetrieve {
      get { return canRetrieve_; }
    }

    /// <summary>Field number for the "CanChange" field.</summary>
    public const int CanChangeFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_canChange_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> canChange_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Should impy delete
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> CanChange {
      get { return canChange_; }
    }

    /// <summary>Field number for the "CanDelete" field.</summary>
    public const int CanDeleteFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_canDelete_codec
        = pb::FieldCodec.ForString(50);
    private readonly pbc::RepeatedField<string> canDelete_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// For the cases where you want someone to be able to clean up, but not extract the content
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> CanDelete {
      get { return canDelete_; }
    }

    /// <summary>Field number for the "UpdatedAt" field.</summary>
    public const int UpdatedAtFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp updatedAt_;
    /// <summary>
    /// For when the streams are moved to new homes with new topic timestamps
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp UpdatedAt {
      get { return updatedAt_; }
      set {
        updatedAt_ = value;
      }
    }

    /// <summary>Field number for the "UpdatedBy" field.</summary>
    public const int UpdatedByFieldNumber = 8;
    private string updatedBy_ = "";
    /// <summary>
    /// Get history from previous updates if needed
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UpdatedBy {
      get { return updatedBy_; }
      set {
        updatedBy_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CorrelationId" field.</summary>
    public const int CorrelationIdFieldNumber = 9;
    private string correlationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CorrelationId {
      get { return correlationId_; }
      set {
        correlationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UserAccessMapping);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UserAccessMapping other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BlobName != other.BlobName) return false;
      if (Owner != other.Owner) return false;
      if(!canChangeAccess_.Equals(other.canChangeAccess_)) return false;
      if(!canRetrieve_.Equals(other.canRetrieve_)) return false;
      if(!canChange_.Equals(other.canChange_)) return false;
      if(!canDelete_.Equals(other.canDelete_)) return false;
      if (!object.Equals(UpdatedAt, other.UpdatedAt)) return false;
      if (UpdatedBy != other.UpdatedBy) return false;
      if (CorrelationId != other.CorrelationId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BlobName.Length != 0) hash ^= BlobName.GetHashCode();
      if (Owner.Length != 0) hash ^= Owner.GetHashCode();
      hash ^= canChangeAccess_.GetHashCode();
      hash ^= canRetrieve_.GetHashCode();
      hash ^= canChange_.GetHashCode();
      hash ^= canDelete_.GetHashCode();
      if (updatedAt_ != null) hash ^= UpdatedAt.GetHashCode();
      if (UpdatedBy.Length != 0) hash ^= UpdatedBy.GetHashCode();
      if (CorrelationId.Length != 0) hash ^= CorrelationId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BlobName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BlobName);
      }
      if (Owner.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Owner);
      }
      canChangeAccess_.WriteTo(output, _repeated_canChangeAccess_codec);
      canRetrieve_.WriteTo(output, _repeated_canRetrieve_codec);
      canChange_.WriteTo(output, _repeated_canChange_codec);
      canDelete_.WriteTo(output, _repeated_canDelete_codec);
      if (updatedAt_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(UpdatedAt);
      }
      if (UpdatedBy.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(UpdatedBy);
      }
      if (CorrelationId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(CorrelationId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BlobName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BlobName);
      }
      if (Owner.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Owner);
      }
      canChangeAccess_.WriteTo(ref output, _repeated_canChangeAccess_codec);
      canRetrieve_.WriteTo(ref output, _repeated_canRetrieve_codec);
      canChange_.WriteTo(ref output, _repeated_canChange_codec);
      canDelete_.WriteTo(ref output, _repeated_canDelete_codec);
      if (updatedAt_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(UpdatedAt);
      }
      if (UpdatedBy.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(UpdatedBy);
      }
      if (CorrelationId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(CorrelationId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BlobName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BlobName);
      }
      if (Owner.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Owner);
      }
      size += canChangeAccess_.CalculateSize(_repeated_canChangeAccess_codec);
      size += canRetrieve_.CalculateSize(_repeated_canRetrieve_codec);
      size += canChange_.CalculateSize(_repeated_canChange_codec);
      size += canDelete_.CalculateSize(_repeated_canDelete_codec);
      if (updatedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdatedAt);
      }
      if (UpdatedBy.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UpdatedBy);
      }
      if (CorrelationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CorrelationId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UserAccessMapping other) {
      if (other == null) {
        return;
      }
      if (other.BlobName.Length != 0) {
        BlobName = other.BlobName;
      }
      if (other.Owner.Length != 0) {
        Owner = other.Owner;
      }
      canChangeAccess_.Add(other.canChangeAccess_);
      canRetrieve_.Add(other.canRetrieve_);
      canChange_.Add(other.canChange_);
      canDelete_.Add(other.canDelete_);
      if (other.updatedAt_ != null) {
        if (updatedAt_ == null) {
          UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        UpdatedAt.MergeFrom(other.UpdatedAt);
      }
      if (other.UpdatedBy.Length != 0) {
        UpdatedBy = other.UpdatedBy;
      }
      if (other.CorrelationId.Length != 0) {
        CorrelationId = other.CorrelationId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            BlobName = input.ReadString();
            break;
          }
          case 18: {
            Owner = input.ReadString();
            break;
          }
          case 26: {
            canChangeAccess_.AddEntriesFrom(input, _repeated_canChangeAccess_codec);
            break;
          }
          case 34: {
            canRetrieve_.AddEntriesFrom(input, _repeated_canRetrieve_codec);
            break;
          }
          case 42: {
            canChange_.AddEntriesFrom(input, _repeated_canChange_codec);
            break;
          }
          case 50: {
            canDelete_.AddEntriesFrom(input, _repeated_canDelete_codec);
            break;
          }
          case 58: {
            if (updatedAt_ == null) {
              UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(UpdatedAt);
            break;
          }
          case 66: {
            UpdatedBy = input.ReadString();
            break;
          }
          case 74: {
            CorrelationId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            BlobName = input.ReadString();
            break;
          }
          case 18: {
            Owner = input.ReadString();
            break;
          }
          case 26: {
            canChangeAccess_.AddEntriesFrom(ref input, _repeated_canChangeAccess_codec);
            break;
          }
          case 34: {
            canRetrieve_.AddEntriesFrom(ref input, _repeated_canRetrieve_codec);
            break;
          }
          case 42: {
            canChange_.AddEntriesFrom(ref input, _repeated_canChange_codec);
            break;
          }
          case 50: {
            canDelete_.AddEntriesFrom(ref input, _repeated_canDelete_codec);
            break;
          }
          case 58: {
            if (updatedAt_ == null) {
              UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(UpdatedAt);
            break;
          }
          case 66: {
            UpdatedBy = input.ReadString();
            break;
          }
          case 74: {
            CorrelationId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
